development:
  adapter: postgresql
  encoding: unicode
  database: itra_development
  pool: 5
  username: postgres
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: itra_test
  pool: 5
  username: postgres
  password: 12345

production:
  adapter: postgresql
  encoding: unicode
  database: itra_production
  pool: 5
  username: postgres
  password: 12345
